backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "gyzz"
    label: "高邮州志"
    folder: "src/pages/gyzz"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "annals-page"}
      - {label: "篇目", name: "title", widget: "string"}
      - label: "所属卷"
        name: "vol"
        widget: "select"
        options:
          - { label: '高郵州志總目', value: 'vol-00' }
          - { label: '輿地志卷之一', value: 'vol-01' }
          - { label: '河渠志卷之二', value: 'vol-02' }
          - { label: '民賦志卷之三', value: 'vol-03' }
          - { label: '食貨志卷之四', value: 'vol-04' }
          - { label: '學校志卷之五', value: 'vol-05' }
          - { label: '典禮志卷之六', value: 'vol-06' }
          - { label: '軍政志卷之七', value: 'vol-07' }
          - { label: '秩官志卷之八', value: 'vol-08' }
          - { label: '選舉志卷之九', value: 'vol-09' }
          - { label: '人物志卷之十', value: 'vol-10' }
          - { label: '藝文志卷之十一', value: 'vol-11' }
          - { label: '雜類志卷之十二', value: 'vol-12' }
      - {label: "篇目番号（2位卷号+2位番号 例：010010，步长 10）", name: "order", widget: "string"}
      - {label: "创建时间", name: "date", widget: "datetime"}
      - {label: "正文", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
